

CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY  1
/

CREATE TABLE ADDRESS (
ID 				NUMBER(19,0) NOT NULL, 
LINE1 			VARCHAR2(255 CHAR), 
LINE2 			VARCHAR2(255 CHAR), 
CITY 			VARCHAR2(255 CHAR), 
STATE 			VARCHAR2(255 CHAR), 
ZIP_CODE 		VARCHAR2(255 CHAR), 
COUNTRY 		VARCHAR2(255 CHAR), 
CREATED_BY 		VARCHAR2(255 CHAR), 
CREATED_DATE 	TIMESTAMP, 
DELETED 		NUMBER(1,0), 
UPDATED_BY 		VARCHAR2(255 CHAR), 
UPDATED_DATE 	TIMESTAMP, 
PRIMARY KEY (ID)
)
/
CREATE TABLE CUSTOMER (
ID 				NUMBER(19,0) NOT NULL, 
EMAIL 			VARCHAR2(255 CHAR), 
NAME 			VARCHAR2(255 CHAR), 
PHONE 			NUMBER(10,0), 
CREATED_BY 		VARCHAR2(255 CHAR), 
CREATED_DATE 	TIMESTAMP, 
DELETED 		NUMBER(1,0), 
UPDATED_BY 		VARCHAR2(255 CHAR), 
UPDATED_DATE 	TIMESTAMP, 
ADDRESS_ID 		NUMBER(19,0), 
PRIMARY KEY (ID)
)
/

ALTER TABLE CUSTOMER ADD CONSTRAINT FK_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS
/


--@undo
drop table customer
/
drop table address
/
