

CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY  1
/

CREATE TABLE PRODUCTS (
ID 				NUMBER(19,0) NOT NULL, 
PRODUCT_ID 		VARCHAR2(255 CHAR), 
QUANTITY 		NUMBER(5,0),
CREATED_BY 		VARCHAR2(255 CHAR), 
CREATED_DATE 	TIMESTAMP, 
DELETED 		NUMBER(1,0), 
UPDATED_BY 		VARCHAR2(255 CHAR), 
UPDATED_DATE 	TIMESTAMP, 
PRIMARY KEY (ID)
)
/